ahoyapi: v2
usage: StreamChop cli tools.
env:
  - .env
commands:
  setup:
    usage: Install pre-commit hooks
    cmd: pre-commit install
  clean:
    usage: Remove all segments and snapshots from the output folder
    cmd: |
      echo "Cleaning output folder..."
      rm -rf output/*/snapshots output/*/*.ts output/*/*.m3u8
      echo "Done."
  profile:
    usage: Compose profile helpers
    imports:
      - .ahoy/profile.ahoy.yml
  docker:
    usage: Docker commands for StreamChop
    imports:
      - .ahoy/docker.ahoy.yml
