ahoyapi: v2
usage: StreamChop cli tools.
env:
  - .env
commands:
  setup:
    usage: Install pre-commit hooks
    cmd: pre-commit install
  docker:
    usage: Docker commands for StreamChop
    imports:
      - .ahoy/docker.ahoy.yml
