---
services:
  chopper_cam_1:
    build: ./chopper
    container_name: chopper-cam-1
    restart: unless-stopped
    environment:
      - RTSP_URL=${CAM1_RTSP_URL}
    volumes:
      - ./output/cam1:/output
